resolver: lts-13.14
packages:
- .
extra-deps:
- lz4-conduit-0.3
- patience-0.2.1.1
- temporary-resourcet-0.1.0.1
- git-0.3.0
- git: https://github.com/e-bigmoon/amazonka-s3-streaming
  commit: 25b4ae8fa0321819c5ac9d6f7a95d6b5b07a77f1
flags:
  amazonka-s3-streaming:
    conduit_1_3: true
